[toolchain]

[features]
seeds = false
skip-lint = false

[programs.localnet]
counter_program = "CjSURa8c1i8KnMsB9kt2SzUsQGQd7yXashgdf5DNu2WN"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "/home/aniket/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
